### ISSUE TITLE
[Not a Bug] Some help if is posible

### ISSUE THREAD

**Issue by andress134** [pguardiario/captchas#3]
**Describe the bug**
Hello sir @pguardiario  i try to use this lib on my script but get some erros idk what is wrong, if u can help me to improve my script.
Thank

Here is my script exemple

```js
const url = process.argv[2],
return new Promise((resolve, reject) => {
page.goto(url, {
	  captchaKey: 'key',
      followAllRedirects: true,
      followOriginalHttpMethod: true,
     });
     })
      .catch((error) => {
       console.log(response.body);
        return reject(error.message);
});
}

setInterval(() => {
      send_req();
    }, 100);
```

**To Reproduce**
Please provide the shortest possible puppeteer/playwright/python+selenium script that reproduces the issue. Leave out any api keys.

**Screenshots**

**Additional context**

**Comment by pguardiario** [comment]
I'm not sure what this is, you're not following the instructions in the readme.
Also the bare minimum I need to troubleshoot an issue is a complete script (with url and requires, etc...)
